debugging: true

db:
    host: host.domain.com
    user: phpipam_dev
    pass: mypassword
    name: phpipam_dev
    port: 3306
    
    ssl: true
    
    mysql_attr:
        ssl_ca: /path/to/cacert.pem
        # ssl_key: null
        # ssl_cert: null
        # ssl_capath: null
        # ssl_cipher: "DHE-RSA-AES256-SHA:AES128-SHA"
